### PR TITLE
Upgrade http dependency

### PR DESCRIPTION
**Pull request by duncaan**
Upgrade http gem to a more recent version.

## Description
Other gems depend on this to be up to date

## Related Issue
https://github.com/chef/chef-telemetry/issues/29

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] I have run the pre-merge tests locally and they pass.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by tas50** [comment]
@duncaan Can you sign this commit off for the DCO so we can accept it? https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco

**Comment by duncaan** [comment]
@tas50 - does this not fall under https://github.com/chef/chef/blob/master/CONTRIBUTING.md#chef-obvious-fix-policy?

**Comment by tas50** [comment]
It certainly could, but you'll need to state that in the commit message then.

**Comment by duncaan** [comment]
@tas50 @marcparadise what needs to happen to get this merged?

**Comment by marcparadise** [comment]
Sorry for the delay, I missed that you'd updated with a DCO on the commit.

**Pull request merged**
